# Generated by Django 4.2.4 on 2023-09-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='events',
        ),
    ]
